"""Generate starter_xml for English «fix the code» tasks from buggy Python."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from flask import g

from app import create_app
from data.fix_tasks_defs import FIX_TASK_DEFS
from data.fix_tasks_en import BUGGY_CODE_EN
from data.translations.en_tasks import TASKS_EN
from runner.checker import check_solution
from runner.python_to_blocks import python_to_blocks
from scripts.reference_solutions_en import REFERENCE_SOLUTIONS_EN

_APP = create_app()


def build_starters() -> dict[str, str]:
    errors: list[str] = []
    starters: dict[str, str] = {}

    for topic_id, defs in FIX_TASK_DEFS.items():
        for item in defs:
            fix_id = item["id"]
            base_id = item["based_on"]
            buggy = BUGGY_CODE_EN.get(fix_id)
            if not buggy:
                errors.append(f"{fix_id}: missing BUGGY_CODE_EN entry")
                continue

            correct = REFERENCE_SOLUTIONS_EN.get(base_id)
            if not correct:
                errors.append(f"{fix_id}: no English reference for {base_id}")
                continue

            en_task = TASKS_EN.get(fix_id)
            if not en_task or "tests" not in en_task:
                errors.append(f"{fix_id}: no English tests in en_tasks")
                continue

            tests = en_task["tests"]

            buggy_result = check_solution(buggy, tests)
            if buggy_result["success"]:
                errors.append(f"{fix_id}: buggy code passes English tests — need a different bug")

            correct_result = check_solution(correct, tests)
            if not correct_result["success"]:
                errors.append(
                    f"{fix_id}: reference {base_id} fails English tests — {correct_result['message']}"
                )
                continue

            try:
                xml = python_to_blocks(buggy)["xml"]
            except Exception as exc:
                errors.append(f"{fix_id}: failed to build XML — {exc}")
                continue

            starters[fix_id] = xml

    if errors:
        print("ERRORS:")
        for err in errors:
            print(" ", err)
        raise SystemExit(1)

    return starters


def write_task_starters(starters: dict[str, str]) -> None:
    out = ROOT / "data" / "task_starters_en.py"
    lines = [
        '"""Starter Blockly XML for English «fix the code» tasks. Generated by build_fix_tasks_en.py."""',
        "",
        "STARTER_XML_EN = {",
    ]
    for fix_id in sorted(starters):
        xml = starters[fix_id]
        lines.append(f'    "{fix_id}": """{xml}""",')
    lines.append("}")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(starters)} starter XML entries to {out}")


if __name__ == "__main__":
    with _APP.app_context():
        with _APP.test_request_context():
            g.locale = "en"
            write_task_starters(build_starters())
